addons:
  postgresql: "9.3"
before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - git config --global user.name 'Travis CI'
  - git config --global user.email 'travis-ci@example.com'
branches:
  only:
    - master
install:
  - travis_retry bin/setup
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.1.7
  - 2.2.3
sudo: false
